version: '3.8'

services:
  cpp:
    image: gcc:latest
    volumes:
      - ./tmp:/app
    working_dir: /app
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    networks:
      - compiler_net

  python:
    image: python:3.9-slim
    volumes:
      - ./tmp:/app
    working_dir: /app
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    networks:
      - compiler_net

  java:
    image: openjdk:11-jdk-slim
    volumes:
      - ./tmp:/app
    working_dir: /app
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    networks:
      - compiler_net

networks:
  compiler_net:
    driver: bridge 